### ISSUE TITLE
Implement Context

### ISSUE THREAD

**Issue by g-easy** [census-instrumentation/opencensus-cpp#212]
Context is an object that holds information (such as Span and TagMap) specific to an operation (such as an  RPC) and propagates it implicitly to child operations, function calls, etc.

Work that needs to be done:

- [x] Implement Context object. #200 
- [x] WithContext: for switching into a Context. #200 
- [x] WithSpan, WithTagMap: for switching information into the Context. #208 #209 
- [ ] GetCurrentSpan: to retrieve from Context. #211 
- [ ] GetCurrentTagMap: to retrieve from Context.
- [ ] Add API for adding tags.
- [ ] Make `Record()` include the current TagMap.
- [ ] Update the gRPC plugin to use the Context API.
- [ ] gRPC: propagate trace context.
- [ ] gRPC: propagate tags.

**Comment by bogdandrutu** [comment]
I think everything is done here in order to do a new release.
